[build]
  command = "npm run build"
  commandOrigin = "config"
  publish: /opt/build/repo/opt/build/repo/build
  publishOrigin = "config"

[[redirects]]
  from = "/signup.html"
  to = "/equipmentclone.html"
  status = 301
redirectsOrigin: config

