[build]
  command = "npm run build"
  commandOrigin = "config"
  publish = "winstonchen3.github.io/node_modules"  # Adjust the path as needed
  publishOrigin = "config"

[[redirects]]
  from = "/signup.html"
  to = "/equipmentclone.html"
  status = 301

# You don't need to specify `redirectsOrigin` separately
