[build]
  command = "npm run build"
  commandOrigin = "config"
  publish = "/"
  publishOrigin = "config"

[[redirects]]
  from = "/signup.html"
  to = "equipmentclone.html"
  status = 301
  force = true
